import {
  MapTrifold,
  ChartBar,
  ShieldCheck,
  ArrowsLeftRight,
  PlusCircle,
  Train,
  Sliders,
  Users,
  User,
  Shield,
  Phone,
  ChatCenteredText,
  FileText,
  Gear,
  Database,
  Palette,
  Notebook,
  SignOut,
  Bell,
  Trash,
  Check,
  X,
  DotsThreeVertical,
  PencilSimple,
  CaretDown,
  CaretLeft,
  CaretRight,
  MagnifyingGlass,
  ArrowUp,
  ArrowDown,
  Info,
  Clock,
  Eye,
  CheckCircle,
  GearFine,
  Wrench,
  Lightning,
  Prohibit,
  ArrowClockwise,
  FloppyDisk,
} from "@phosphor-icons/react";

export const Icons = {
  Depot: MapTrifold,
  Dashboard: ChartBar,
  Approvals: ShieldCheck,
  History: ArrowsLeftRight,
  NewManovr: PlusCircle,
  Trains: Train,
  Lines: Sliders,
  Users: Users,
  Roles: Shield,
  Phonebook: Phone,
  Profile: User,
  Tickets: ChatCenteredText,
  Reports: FileText,
  Settings: Gear,
  Lookups: Database,
  Branding: Palette,
  Audit: Notebook,
  Backup: Database,
  Logout: SignOut,
  Bell: Bell,
  Trash: Trash,
  Check: Check,
  X: X,
  Dots: DotsThreeVertical,
  Edit: PencilSimple,
  CaretDown: CaretDown,
  CaretLeft: CaretLeft,
  CaretRight: CaretRight,
  Search: MagnifyingGlass,
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  Info: Info,
  Clock: Clock,
  Eye: Eye,
  CheckCircle: CheckCircle,
  GearFive: GearFine,
  Refresh: ArrowClockwise,
  Save: FloppyDisk,
};

// آیکون‌های وضعیت قطار — استفاده در نمای دوبعدی و سه‌بعدی پایانه
export const StatusIcon = {
  ready: CheckCircle,
  repair: Wrench,
  dispatch: Lightning,
  inactive: Prohibit,
} as const;

export type TrainStatus = 1 | 2 | 3 | 4;
export const statusIconFor = (s: number) =>
  s === 2 ? StatusIcon.repair : s === 3 ? StatusIcon.inactive : s === 4 ? StatusIcon.dispatch : StatusIcon.ready;

